### ISSUE TITLE
Error: Plugin/Preset files are not allowed to export objects, only functions.

### ISSUE THREAD

**Issue by janbaykara** [SectorLabs/babel-plugin-transform-named-imports#5]
```
ERROR in ./react-entry.js
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/Jan/Sites/gyana-ai-client/src/react/node_modules/babel-plugin-transform-named-imports/src/index.js
    at createDescriptor (/Users/Jan/Sites/gyana-ai-client/src/react/node_modules/@babel/core/lib/config/config-descriptors.js:181:11)
    at /Users/Jan/Sites/gyana-ai-client/src/react/node_modules/@babel/core/lib/config/config-descriptors.js:106:12
    at Array.map (<anonymous>)
    at createDescriptors (/Users/Jan/Sites/gyana-ai-client/src/react/node_modules/@babel/core/lib/config/config-descriptors.js:105:27)
    at createPluginDescriptors (/Users/Jan/Sites/gyana-ai-client/src/react/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at /Users/Jan/Sites/gyana-ai-client/src/react/node_modules/@babel/core/lib/config/config-descriptors.js:52:19
    at plugins (/Users/Jan/Sites/gyana-ai-client/src/react/node_modules/@babel/core/lib/config/config-descriptors.js:42:25)
    at mergeChainOpts (/Users/Jan/Sites/gyana-ai-client/src/react/node_modules/@babel/core/lib/config/config-chain.js:322:68)
    at /Users/Jan/Sites/gyana-ai-client/src/react/node_modules/@babel/core/lib/config/config-chain.js:277:7
    at buildRootChain (/Users/Jan/Sites/gyana-ai-client/src/react/node_modules/@babel/core/lib/config/config-chain.js:111:20)
 @ multi ./react-entry webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr webpack/hot/only-dev-server react-hot-loader/patch
ℹ ｢wdm｣: Failed to compile.
Webpack Bundle Analyzer is star
```

**Comment by Photonios** [comment]
This has been resolved in the latest version.
